### ISSUE TITLE
Publish for composer

### ISSUE THREAD

**Issue by rodrigo-arias** [hsimah-services/wp-graphql-metabox#22]
Hi,

Great job with the Meta Box integration, it really saved my life.

Do you plan to expose it to composer on a platform like Packagist?

Thank you

**Comment by hsimah** [comment]
That's a great idea. I'll see what needs doing and let you know.

**Comment by hsimah** [comment]
It's up. I will improve the dependencies in future works: https://packagist.org/packages/hsimah-services/wp-graphql-metabox

**Comment by rodrigo-arias** [comment]
Awesome, it will be great to also have the integration with MB Relationships. Thanks!
