### ISSUE TITLE
Support for text_list with clone option

### ISSUE THREAD

**Issue by NilsEngelbach** [hsimah-services/wp-graphql-metabox#29]
If you define a text_list with the option 'clone' => true the graphql model should be an array of string arrays otherwise you will get an graphql error when quering the custom fields.

```php
function ingredients_register_meta_boxes( $meta_boxes ) {
	$meta_boxes[] = [
		'title'      => esc_html__( 'Ingredients' ),
		'id'         => 'zutaten',
		'post_types' => ['ingredients'],
		'context'    => 'normal',
		'priority'   => 'high',
		'fields'     => [
			[
				'type'    => 'text_list',
				'id'      => 'ingredients',
				'name'    => esc_html__( 'Ingredients' ),
				'desc'    => esc_html__( 'Specify the ingredients' ),
				'clone'   => true,
				'options' => [
					'100'    => 'Amount',
                                        'ml'     => 'Unit',
                                        'Water' => 'Name',
				],
				'graphql_name' => 'ingredients',
			],
		],
	];

	return $meta_boxes;
}

add_filter( 'rwmb_meta_boxes', 'ingredients_register_meta_boxes' );
```

I also provided a fix with this PR:
#28

**Comment by hsimah** [comment]
thanks @NilsEngelbach for this - I haven't used clone fields so this was not even on my radar. Can any other types be cloned?

**Comment by NilsEngelbach** [comment]
I only found the issue because i was using the `text_list` so far.

The docs show it is part of the common settings so i guess every field could possibly do it: https://docs.metabox.io/field-settings/#common-settings

When looking at the online generator it is configured for many components: https://metabox.io/online-generator/ 

So should we try to use a more general approach?

**Comment by hsimah** [comment]
Thanks for the in depth research! I'll take a look and see what I like. The whole thing can use some refactoring.

**Comment by hsimah** [comment]
I've pushed a fix to make all fields cloneable/multiple. This does not handle the case of clone and multiple. I will have to generate a field for that and test.

**Comment by hsimah** [comment]
It was actually easier than I expected to pull this off.

**Comment by NilsEngelbach** [comment]
Cool! I will update the plugin and test it. I also found one line where i am not sure if it also needs to be updated in your PR.

There are only really few fields that actually support multiple and cloned e.g. `Select`, `Select Advanced` and `Image Select`. But shouldn`t it be possible to also implement this is a general way, so if it is both clonable and multiple than it must be a `['list_of' => ['list_of' => <type> ]]`?

**Comment by hsimah** [comment]
Yeah the code will do this:
- Check GraphQL type (ie `String`)
- Check if `multiple`, wrap in `['list_of']`
- Check if `clone`, wrap in `['list_of']`

So if both are true you'll get a list of list of type situation.

It worked for my use case, a list of posts.

**Comment by NilsEngelbach** [comment]
A true i thought there was a return!
